### ISSUE TITLE
ModuleNotFoundError: No module named 'docx'

### ISSUE THREAD

**Issue by My12123** [alicewish/MomoTranslator#10]
![2023-04-25_13-24-48](https://user-images.githubusercontent.com/49092250/234249951-e0b015a9-1426-4210-b120-aa85bf3f87fc.png)
```python
(venv) F:\MomoTranslator>python pyqt5_momotranslator.py
Traceback (most recent call last):
  File "F:\MomoTranslator\pyqt5_momotranslator.py", line 48, in <module>
    from docx import Document
ModuleNotFoundError: No module named 'docx'
```

**Comment by alicewish** [comment]
fixed in https://github.com/alicewish/MomoTranslator/commit/3810f1ebc2e2a6fb023c052f6ffc451783df1c11
