### ISSUE TITLE
vertical变量名报错不存在

### ISSUE THREAD

**Issue by tyfhxn** [alicewish/MomoTranslator#16]
我的python版本为：Python 3.10.11
进行到文字识别的时候会报错，截图如下
![屏幕截图 2023-07-01 232536](https://github.com/alicewish/MomoTranslator/assets/58685206/ce745f24-4a54-4bd8-bf03-a908b51ca7d1)
翻译用的原图如下：
![RCO004_1688175593](https://github.com/alicewish/MomoTranslator/assets/58685206/48beca28-9920-419b-9539-f54c7272d166)

**Comment by Projmix** [comment]
I had a similar error 
To fix it, all you have to do is change this line
recognized_text = ocr_by_tesseract(single_cnt.cropped_image, self.media_language, False) # 3 parameters change to true if Japanese comic book
`
Traceback (most recent call last):
  File "D:\Code\TEST\ocr\MomoTranslator\pyqt5_momotranslator.py", line 3049, in start_task
    self.step2_OCR()
  File "D:\Code\TEST\ocr\MomoTranslator\pyqt5_momotranslator.py", line 2913, in step2_OCR
    recognized_text = ocr_by_tesseract(single_cnt.cropped_image, self.media_language, vertical)
NameError: name 'vertical' is not defined
`
我也遇到过类似的错误。
要解决这个问题，你只需修改这一行
recognised_text = ocr_by_tesseract(single_cnt.cropped_image, self.media_language, False) # 如果是日文漫画书，3 个参数改为 true

**Comment by Projmix** [comment]
> 我的python版本为：Python 3.10.11 进行到文字识别的时候会报错，截图如下 ![屏幕截图 2023-07-01 232536](https://user-images.githubusercontent.com/58685206/250288602-ce745f24-4a54-4bd8-bf03-a908b51ca7d1.png) 翻译用的原图如下： ![RCO004_1688175593](https://user-images.githubusercontent.com/58685206/250288611-48beca28-9920-419b-9539-f54c7272d166.jpg)

I had a similar error 
To fix it, all you have to do is change this line
FIX:
`
recognized_text = ocr_by_tesseract(single_cnt.cropped_image, self.media_language, False) # 3 parameters change to true if Japanese comic book
`
ERROR:
`
Traceback (most recent call last):
  File "D:\Code\TEST\ocr\MomoTranslator\pyqt5_momotranslator.py", line 3049, in start_task
    self.step2_OCR()
  File "D:\Code\TEST\ocr\MomoTranslator\pyqt5_momotranslator.py", line 2913, in step2_OCR
    recognized_text = ocr_by_tesseract(single_cnt.cropped_image, self.media_language, vertical)
NameError: name 'vertical' is not defined
`
我也遇到过类似的错误。
要解决这个问题，你只需修改这一行
FIX:
`
recognised_text = ocr_by_tesseract(single_cnt.cropped_image, self.media_language, False) # 如果是日文漫画书，3 个参数改为 true
`

**Comment by alicewish** [comment]
已更新，需重新测试是否存在bug
