### ISSUE TITLE
请问技术上能不能编译成exe文件

### ISSUE THREAD

**Issue by 2529912523X** [alicewish/MomoTranslator#19]
pythin版本3.12，运行pip install -r requirements.txt时报错，所以我就手动一个个安装。在安装到easyocr和pytorch时安装了很多遍也上网查了教程但还是失败，所以就想问问是否能编译，谢谢。

**Comment by alicewish** [comment]
你如果装不上，编译也无法解决装不上，建议转3.10或者把用到easyocr和pytorch的代码删掉（删掉也能用）
