### ISSUE TITLE
cv2.error: OpenCV(4.6.0) /Users/xperience/actions-runner/_work/opencv-python/opencv-python/opencv/modules/core/src/arithm.cpp:1742: error: (-209:Sizes of input arguments do not match) The lower boundary is neither an array of the same size and same type as src, nor a scalar in function 'inRange'

### ISSUE THREAD

**Issue by jaclla** [alicewish/MomoTranslator#24]
mac m1 环境，点击开始按钮后后台报错
![image](https://github.com/alicewish/MomoTranslator/assets/34511671/331d8423-cce2-4364-a31d-b48275d17efc)
![image](https://github.com/alicewish/MomoTranslator/assets/34511671/bbaaa0f7-eeac-4c9b-979c-1442c20697b3)
![image](https://github.com/alicewish/MomoTranslator/assets/34511671/8454f365-6428-479e-a273-fc111fa074a5)

**Comment by alicewish** [comment]
图源选几张图片作为附件传上来

**Comment by jaclla** [comment]
![65393908_p2](https://github.com/alicewish/MomoTranslator/assets/34511671/256c45a5-17a1-4c38-9f60-c1d3907f70a4)

**Comment by jaclla** [comment]
![65393908_p3](https://github.com/alicewish/MomoTranslator/assets/34511671/320e8e95-4c34-4504-b99d-b75947ed03d0)

**Comment by alicewish** [comment]
可以在yml里改成do_add_frame: false
