### ISSUE TITLE
您好，运行过程中似乎缺少一个资源

### ISSUE THREAD

**Issue by tohsakrat** [alicewish/MomoTranslator#27]
如题
![image](https://github.com/alicewish/MomoTranslator/assets/45536831/0cb74ba1-5679-4321-b820-fb1bbfc3a75f)
我按照提示寻找了源，并没有发现一个叫words的包。请问我应该如何补全它呢？https://www.nltk.org/nltk_data/

**Comment by alicewish** [comment]
图里红字就是下载方式
