### ISSUE TITLE
Qt_6_PRIVATE_API Erro

### ISSUE THREAD

**Issue by wwardaww** [alicewish/MomoTranslator#29]
![image](https://github.com/alicewish/MomoTranslator/assets/12273655/54c28833-9f25-444f-ab20-cc65c60c580b)

Hi, we cannot open the gui 
```
Traceback (most recent call last):
  File "/media/arda/E64E3CD94E3CA3E91/Projeler/MomoTranslator/pyqt5_momotranslator.py", line 45, in <module>
    from PyQt6.QtCore import QPointF, QRectF, QSettings, QSize, QTranslator, Qt, pyqtSignal
ImportError: /home/arda/.local/lib/python3.10/site-packages/PyQt6/QtCore.abi3.so: undefined symbol: _ZN14QReadWriteLock16destroyRecursiveEP21QReadWriteLockPrivate, version Qt_6_PRIVATE_API
```

**Comment by alicewish** [comment]
What device and OS are you using?

**Comment by wwardaww** [comment]
Ubuntu 22.04 and desktop

**Comment by wwardaww** [comment]
and also im using python 3.10

**Comment by wwardaww** [comment]
hi i found it!! i install pyqt6==6.2.0 and then i un comment nltk but now i have another problem:

```
Traceback (most recent call last):
  File "/media/arda/E64E3CD94E3CA3E91/Projeler/MomoTranslator/pyqt5_momotranslator.py", line 9315, in <module>
    msyh_font20 = ImageFont.truetype(msyh_font_ttc, 20)
  File "/home/arda/.local/lib/python3.10/site-packages/PIL/ImageFont.py", line 797, in truetype
    return freetype(font)
  File "/home/arda/.local/lib/python3.10/site-packages/PIL/ImageFont.py", line 794, in freetype
    return FreeTypeFont(font, size, index, encoding, layout_engine)
  File "/home/arda/.local/lib/python3.10/site-packages/PIL/ImageFont.py", line 230, in __init__
    load_from_bytes(font)
  File "/home/arda/.local/lib/python3.10/site-packages/PIL/ImageFont.py", line 210, in load_from_bytes
    self.font_bytes = f.read()
AttributeError: 'NoneType' object has no attribute 'read'
```

![image](https://github.com/alicewish/MomoTranslator/assets/12273655/a83124e1-af0c-4184-a35e-5213d71a791a)

**Comment by wwardaww** [comment]
Hi i fix the all issue but interface is chiniese is there a way to change it or should i translate it? i willopen a pr for fixes it's looks like when program cant found the font it's fails

**Comment by alicewish** [comment]
comment `lang_code = 'zh_CN'`
uncomment `# lang_code = 'en_US'`

**Comment by wwardaww** [comment]
now i can't access gui bu i cant process this image

![RCO007_1663976825](https://github.com/alicewish/MomoTranslator/assets/12273655/e8118492-4643-4c8d-bb0c-f3843fce82e6)

console output

![image](https://github.com/alicewish/MomoTranslator/assets/12273655/b23432f2-435b-4596-9664-346e7529f727)



trace:

![image](https://github.com/alicewish/MomoTranslator/assets/12273655/84ce0822-02e0-44e4-88f2-0289cca16a89)


gui: 

![image](https://github.com/alicewish/MomoTranslator/assets/12273655/c6c7e000-d12e-45c3-a0e0-7ec25b3f570c)


check_pts image:

![check_pts](https://github.com/alicewish/MomoTranslator/assets/12273655/1275d546-ba0e-4f85-b529-86854f6ca821)

**Comment by alicewish** [comment]
There is one bubble so there should only be one textblock but the check_pts image shows two textblocks, one with blue filling and one with white filling.
Give me the whole name of the scan file, I'll use it to find the file and get a proper WLB_ext_px value.

**Comment by wwardaww** [comment]
what is scan file? iamge name is : RCO003_1663976825.jpg

**Comment by alicewish** [comment]
In the config file, when using `do_mode: 'do_dev_folder'`, change `folder_name` to your actual folder name, also make sure there is a corresponding folder under ComicProcess folder with that name.

**Comment by alicewish** [comment]
Search for `comictextdetector.pt.onnx` in the code and you'll get the path. Or you can change the path in the code.

**Comment by alicewish** [comment]
In the config file, change `target_lang: 'zh-CN'` to your desired language, and make sure it is valid.
See more at https://github.com/nidhaloff/deep-translator

The ChatGPT web translator is written for Mac automation and does not work on any other system.
