### ISSUE TITLE
Outscreen bubbles are not detecting

### ISSUE THREAD

**Issue by wwardaww** [alicewish/MomoTranslator#30]
Hi some out screen bubbles are not detecting:

original image:

 
![image](https://github.com/alicewish/MomoTranslator/assets/12273655/eab4a148-875c-4641-b318-e2d300619cbe)

detection image:
![image](https://github.com/alicewish/MomoTranslator/assets/12273655/6a0d2dbe-c938-4ed9-9467-6fbd1d2cf121)

**Comment by alicewish** [comment]
You need to put XXX-加框.jpg in your folder, which would be generated in step 1.

**Comment by wwardaww** [comment]
there is no XXX-加框.jpg bu here another step images
![test](https://github.com/alicewish/MomoTranslator/assets/12273655/fcb66215-bd37-49de-bf56-84ea043520db)

![test2](https://github.com/alicewish/MomoTranslator/assets/12273655/cbea1e0e-4035-40ff-9949-62f455c46313)

**Comment by alicewish** [comment]
![287685320-eab4a148-875c-4641-b318-e2d300619cbe-画格](https://github.com/alicewish/MomoTranslator/assets/11379080/ebd59514-ed97-4ccc-b224-e70e32608b0b)
![287685320-eab4a148-875c-4641-b318-e2d300619cbe-加框](https://github.com/alicewish/MomoTranslator/assets/11379080/f16f138b-ae2d-4f5e-8df6-fda0496dcda9)
![287685320-eab4a148-875c-4641-b318-e2d300619cbe-CTD](https://github.com/alicewish/MomoTranslator/assets/11379080/4cd85753-a8b4-4bd6-832e-4ec43210a112)
![287685320-eab4a148-875c-4641-b318-e2d300619cbe-ffffff-white~000000-black](https://github.com/alicewish/MomoTranslator/assets/11379080/9e3fb2fb-9a18-4b7f-8345-33d4ad3dbf1a)
![287685320-eab4a148-875c-4641-b318-e2d300619cbe-Mask-ffffff-white~000000-black](https://github.com/alicewish/MomoTranslator/assets/11379080/1ed86340-711e-46a5-96da-a83099eb91f4)
![287685320-eab4a148-875c-4641-b318-e2d300619cbe-TextBlock-ffffff-white~000000-black](https://github.com/alicewish/MomoTranslator/assets/11379080/c3446934-3d49-4289-960f-9f7315387547)

**Comment by alicewish** [comment]
It should be generated in step 1.

**Comment by alicewish** [comment]
Update the code and try again.
Also, one folder can only use all png or all jpg, not mixed.

**Comment by wwardaww** [comment]
Hi, i have new bug (of course :d)

I cant process this image :
![1](https://github.com/alicewish/MomoTranslator/assets/12273655/a56026d7-61a5-429e-8cc5-8424fca67745)


its throw this error:
![image](https://github.com/alicewish/MomoTranslator/assets/12273655/da679cde-2960-4a2f-a693-d4d187764b0f)

**Comment by alicewish** [comment]
In config file comment `- 'ffffff-15~000000-60' # 白底黑字`,
uncomment `- '000000-15~ffffff-60' # 黑底白字`,
and try again.
