### ISSUE TITLE
ModuleNotFoundError: No module named 'aip'

### ISSUE THREAD

**Issue by My12123** [alicewish/MomoTranslator#6]
![2023-04-23_20-36-13](https://user-images.githubusercontent.com/49092250/233855708-14b3a545-8c5f-4ac8-815e-4096b1d0e8cd.png)
```python
(venv) F:\MomoTranslator>python pyqt5_momotranslator.py
Traceback (most recent call last):
  File "F:\MomoTranslator\pyqt5_momotranslator.py", line 43, in <module>
    from aip import AipOcr
ModuleNotFoundError: No module named 'aip'
``` 
![2023-04-23_20-47-43](https://user-images.githubusercontent.com/49092250/233856154-f7eb10bc-afc7-4be7-910f-fa8399f6621b.png)

**Comment by alicewish** [comment]
fixed in https://github.com/alicewish/MomoTranslator/commit/3e739c14b615ca56bed75680c714325c02b97afa
